# Generated by Django 3.2 on 2023-05-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speed90Weight', models.FloatField()),
                ('ShorelineDistWeight', models.FloatField()),
                ('MilitaryDistWeight', models.FloatField()),
                ('ProtectedAreaDistWeight', models.FloatField()),
                ('Landing19Weight', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Maps',
            },
        ),
    ]
