# Generated by Django 3.2.16 on 2023-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='Landing19',
            new_name='Landing19Weight',
        ),
        migrations.RenameField(
            model_name='maps',
            old_name='MilitaryDist',
            new_name='MilitaryDistWeight',
        ),
        migrations.RenameField(
            model_name='maps',
            old_name='ShorelineDist',
            new_name='ShorelineDistWeight',
        ),
        migrations.RemoveField(
            model_name='maps',
            name='Speed90',
        ),
        migrations.AddField(
            model_name='maps',
            name='Speed90Weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
